## Introduction and Rationale

* The 2AFC looking-while-listening paradigm  [LWL; @FernaldLWL] has become widely used to examine lexical processing in young children.
* The speed at which children look to familiar objects when hearing the object-name at 18 months reliably predicts vocabulary size up to 8 years of age [@MarchmanLangOutcomes].  
    - However, these reaction time measures are not easily obtained.
    - Reaction time is a measure of how quickly a child looks to a picture when its object name is presented.  Therefore, reaction time can be measured only on trials where the child is _not_ looking at the target picture at the onset of the target word.
    - In a 2AFC paradigm, only about 50% of trials provide reaction time data. 
    - Usually, even fewer trials provide reaction time data because there are always some trials where young children are not fixating on a picture at target word onset.
    - This is a considerable problem, given the small number of trials in LWL studies (usually between 24 and 36).
* Adults can be instructed to fixate on a central orienting stimuli, but young children cannot be similarly instructed.
* This study used an animated centering stimulus in an attempt to increase the number of trials with useable reaction times.


The looking-while-listening paradigm [LWL; @FernaldLWL] uses eye-tracking to study lexical comprehension in young children. In this procedure, two images are presented on a computer screen followed by a prompt to look at one of the images. The data gathered through eye-tracking not only records _where_ the child looks onscreen but _when_ the child fixates on a particular image. The latency between the onset of a speech stimulus and an appropriate change of gaze location provides a measure of how rapidly the child accesses the word's lexical representation. Reaction time is related to vocabulary size in young children and is also predictive of later language abilities [@FernaldHalfAWord; ]. 

Reaction times provide valuable information about the real-time processing of speech signal in children, but these data are not easily obtained. In a 2-alternative forced choice (2AFC) LWL paradigm, there is a 50% chance the child will be fixated on the target image at onset of the speech stimulus, so only half the trials will provide latency data. This problem is readily resolved in studies with adults by instructing participants to fixate on a central orienting image until they hear the stimulus. Unfortunately, young children cannot be similarly instructed.

In this study, we modified the LWL paradigm to include an animated centering stimulus in order to increase the number of trials with meaningful reaction time data. We hypothesized that the orienting animations will increase the "quality" of the eye-tracking data but may also introduce additional task demands that hinder response time and reduce accuracy. 

## Methods

### Participants
The participants were fifty 30-- to 48-month-old children, 25 per condition (with and without the central fixation point). All participants passed a hearing screening and had age-appropriate speech and language, according to parent report. 

### Procedure
A 2AFC mispronunciation experiment was used in condition. In this experiment, children saw pictures of a familiar and an unfamiliar object and heard three types of stimuli in a carrier phrase: familiar real words, one-feature mispronunciations (_dog_ vs. _tog_), and nonwords (/veif/).  Children also received an expressive vocabulary test (EVT-2, Williams, 2007).

### Statistical Analysis
The log-odds of looking to the familiar object was the dependent variable.  We used a growth curve model to model how children’s eye gaze patterns were related to their expressive vocabulary size (Mirman et al., 2008)

## Results and Discussion





## References
